# Generated by Django 3.1.7 on 2021-03-24 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eur_balance', models.FloatField(blank=True, null=True)),
                ('bitcoin_balance', models.FloatField(blank=True, null=True)),
                ('ethereum_balance', models.FloatField(blank=True, null=True)),
                ('cardano_balance', models.FloatField(blank=True, null=True)),
                ('litecoin_balance', models.FloatField(blank=True, null=True)),
                ('polkadot_balance', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
            options={
                'db_table': 'Wallet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('card_id', models.CharField(max_length=255, unique=True)),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('debet_card_number', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
            options={
                'db_table': 'Personal_info',
                'managed': True,
            },
        ),
    ]
